export enum APP_CONSTANTS {
    USER_KEY = 'user_key',
}

export const COMMON_CONSTANTS = {
    REGEX_USERNAME: new RegExp(/^$|[a-zA-Z0-9_]+$/),
    REGEX_EMAIL: new RegExp(/^(|[a-zA-Z0-9_.+-]+@([a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]*\.)+[a-zA-Z]{2,})$/),
    //REGEX_NAME_WITHOUT_SPECIAL_CHARACTER: new RegExp(/^(|[\p{L}\p{Nd}\s]{0,})$/u),
    TIMEZONE: 'UTC',
    START_TIME_STR: '00:00:00',
    PERCENT_CHAR: '%',
    PIPE_CHAR: '|',
    MAX_COMMENTS_IN_A_PAGE: 3
}

export const S3_UPLOAD_FOLDER = {
    UPLOAD: 'upload'
}

export const SOCKET_MESSAGES = {
    CLIENT_MESSAGE: 'client-message',
    CLIENT_ADD_COMMENT: 'client-add-comment',
    CLIENT_UPDATE_COMMENT: 'client-update-comment',
    CLIENT_LIKE_POST: 'client-like-post',
    CLIENT_ADD_FRIEND: 'client-add-friend',
    CLIENT_ACCEPT_FRIEND: 'client-accept-friend',
    CLIENT_CANCEL_FRIEND_REQUEST: 'client-cancel-friend-request',
    CLIENT_DELETE_FRIEND_REQUEST: 'client-delete-friend-request',
}

export const SOCKET_MESSAGE_TYPES = {
    MESSAGE_NOTIFICATION_RECEIVED: 'MESSAGE_NOTIFICATION_RECEIVED',
    ADD_COMMENT_MESSAGE_FROM_SERVER: 'ADD_COMMENT_MESSAGE_FROM_SERVER',
    ADD_COMMENT_NOTIFICATION_MESSAGE_FROM_SERVER: 'ADD_COMMENT_NOTIFICATION_MESSAGE_FROM_SERVER',
    UPDATE_COMMENT_MESSAGE_FROM_SERVER: 'UPDATE_COMMENT_MESSAGE_FROM_SERVER',
    LIKE_POST_MESSAGE_FROM_SERVER: 'LIKE_POST_MESSAGE_FROM_SERVER',
    LIKE_POST_NOTIFICATION_MESSAGE_FROM_SERVER: 'LIKE_POST_NOTIFICATION_MESSAGE_FROM_SERVER',
    ADD_FRIEND_SOCKET_HANDLER: 'ADD_FRIEND_SOCKET_HANDLER',
    ADD_FRIEND_MESSAGE_FROM_SERVER: 'ADD_FRIEND_MESSAGE_FROM_SERVER',
    ADD_FRIEND_NOTIFICATION_MESSAGE_FROM_SERVER: 'ADD_FRIEND_NOTIFICATION_MESSAGE_FROM_SERVER',
    ACCEPT_FRIEND_SOCKET_HANDLER: 'ACCEPT_FRIEND_SOCKET_HANDLER',
    ACCEPT_FRIEND_MESSAGE_FROM_SERVER: 'ACCEPT_FRIEND_MESSAGE_FROM_SERVER',
    ACCEPT_FRIEND_NOTIFICATION_MESSAGE_FROM_SERVER: 'ACCEPT_FRIEND_NOTIFICATION_MESSAGE_FROM_SERVER',
    CANCEL_FRIEND_REQUEST_SOCKET_HANDLER: 'CANCEL_FRIEND_REQUEST_SOCKET_HANDLER',
    CANCEL_FRIEND_REQUEST_MESSAGE_FROM_SERVER: 'CANCEL_FRIEND_REQUEST_MESSAGE_FROM_SERVER',
    DELETE_FRIEND_REQUEST_SOCKET_HANDLER: 'DELETE_FRIEND_REQUEST_SOCKET_HANDLER',
    DELETE_FRIEND_REQUEST_MESSAGE_FROM_SERVER: 'DELETE_FRIEND_REQUEST_MESSAGE_FROM_SERVER',
    
} 

export enum ORDER_BY {
    DESC = 'DESC',
    ASC = 'ASC'
}

export enum USER_TYPE_ENUM {
    PERSONAL = 'Personal',
    BUSINESS = 'Business'
}

export enum USER_STATUS_ENUM {
    ACTIVE = 'Active',
    INACTIVE = 'Inactive'
}

export enum GENDER_ENUM {
    MALE = 'Male',
    FEMALE = 'Female',
    OTHER = 'Other'
}

export enum PRIVACY_SETTING {
    ONLY_ME = 'Only me',
    PUBLIC = 'Public',
    FRIENDS = 'Friends',
    FRIENDS_EXCEPT = 'Friends except',
    SPECIFIC_FRIENDS = 'Specific friends'
}

export enum LANGUAGE_ENUM {
    VIETNAMESE = 'VI',
    ENGLISH = 'ENG'
}

export enum RELATIONSHIP_TYPE_ENUM {
    FRIEND = 'FRIEND',
    FRIEND_REQUEST_RECEIVER = 'FRIEND_REQUEST_RECEIVER',
    FRIEND_REQUEST_SENDER = 'FRIEND_REQUEST_SENDER'
}

export enum NOTIFICATION_ACTION_ENUM {
    LIKE = 'LIKE',
    COMMENT = 'COMMENT',
    SEND_FRIEND_REQUEST = 'SEND_FRIEND_REQUEST',
    ACCEPT_FRIEND_REQUEST = 'ACCEPT_FRIEND_REQUEST'
}

export enum OBJECT_TYPE_ENUM {
    POST = 'POST',
    FRIEND_REQUEST = 'FRIEND_REQUEST',
    USER = 'USER'
}