import { MigrationInterface, QueryRunner } from "typeorm";

export class migration2022030321646325170726 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`INSERT INTO city(Id, name, is_active, created_by, updated_by) VALUES 
            (1, 'An Giang', 1, '', ''),
            (2, 'Bà Rịa - Vũng Tàu', 1, '', ''),
            (3, 'Bạc Liêu', 1, '', ''),
            (4, 'Bắc Giang', 1, '', ''),
            (5, 'Bắc Kạn', 1, '', ''),
            (6, 'Bắc Ninh', 1, '', ''),
            (7, 'Bến Tre', 1, '', ''),
            (8, 'Bình Dương', 1, '', ''),
            (9, 'Bình Định', 1, '', ''),
            (10, 'Bình Phước', 1, '', ''),
            (11, 'Bình Thuận', 1, '', ''),
            (12, 'Cà Mau', 1, '', ''),
            (13, 'Cao Bằng', 1, '', ''),
            (14, 'Cần Thơ', 1, '', ''),
            (15, 'Đà Nẵng', 1, '', ''),
            (16, 'Đắk Lắk', 1, '', ''),
            (17, 'Đắk Nông', 1, '', ''),
            (18, 'Điện Biên', 1, '', ''),
            (19, 'Đồng Nai', 1, '', ''),
            (20, 'Đồng Tháp', 1, '', ''),
            (21, 'Gia Lai', 1, '', ''),
            (22, 'Hà Giang', 1, '', ''),
            (23, 'Hà Nam', 1, '', ''),
            (24, 'Hà Nội', 1, '', ''),
            (25, 'Hà Tĩnh', 1, '', ''),
            (26, 'Hải Dương', 1, '', ''),
            (27, 'Hải Phòng', 1, '', ''),
            (28, 'Hậu Giang', 1, '', ''),
            (29, 'Hòa Bình', 1, '', ''),
            (30, 'Thành phố Hồ Chí Minh', 1, '', ''),
            (31, 'Hưng Yên', 1, '', ''),
            (32, 'Khánh Hòa', 1, '', ''),
            (33, 'Kiên Giang', 1, '', ''),
            (34, 'Kon Tum', 1, '', ''),
            (35, 'Lai Châu', 1, '', ''),
            (36, 'Lạng Sơn', 1, '', ''),
            (37, 'Lào Cai', 1, '', ''),
            (38, 'Lâm Đồng', 1, '', ''),
            (39, 'Long An', 1, '', ''),
            (40, 'Nam Định', 1, '', ''),
            (41, 'Nghệ An', 1, '', ''),
            (42, 'Ninh Bình', 1, '', ''),
            (43, 'Ninh Thuận', 1, '', ''),
            (44, 'Phú Thọ', 1, '', ''),
            (45, 'Phú Yên', 1, '', ''),
            (46, 'Quảng Bình', 1, '', ''),
            (47, 'Quảng Nam', 1, '', ''),
            (48, 'Quảng Ngãi', 1, '', ''),
            (49, 'Quảng Ninh', 1, '', ''),
            (50, 'Quảng Trị', 1, '', ''),
            (51, 'Sóc Trăng', 1, '', ''),
            (52, 'Sơn La', 1, '', ''),
            (53, 'Tây Ninh', 1, '', ''),
            (54, 'Thái Bình', 1, '', ''),
            (55, 'Thái Nguyên', 1, '', ''),
            (56, 'Thanh Hóa', 1, '', ''),
            (57, 'Thừa Thiên Huế', 1, '', ''),
            (58, 'Tiền Giang', 1, '', ''),
            (59, 'Trà Vinh', 1, '', ''),
            (60, 'Tuyên Quang', 1, '', ''),
            (61, 'Vĩnh Long', 1, '', ''),
            (62, 'Vĩnh Phúc', 1, '', ''),
            (63, 'Yên Bái', 1, '', '')
            `);
        await queryRunner.query(`INSERT INTO school(Id, name, is_active, created_by, updated_by) VALUES 
            (1, 'THPT Cầu Kè', 1, '', ''),
            (2, 'THPT Châu Văn Liêm', 1, '', ''),
            (3, 'THPT FPT', 1, '', ''),
            (4, 'THPT Chuyên Lý Tự Trọng', 1, '', ''),
            (5, 'THPT Bùi Hữu Nghĩa', 1, '', ''),
            (6, 'THPT Thực hành Sư Phạm', 1, '', ''),
            (7, 'THPT Nguyễn Văn Thoại', 1, '', ''),
            (8, 'THPT Chuyên Nguyễn Thiện Thành', 1, '', ''),
            (9, 'THPT Chuyên Lê Hồng Phong', 1, '', ''),
            (10, 'THPT Hà Nội - Amsterdam', 1, '', ''),
            (11, 'THPT Marie Curie', 1, '', ''),
            (12, 'THPT Nguyễn Khuyến', 1, '', '')
            `);
        await queryRunner.query(`INSERT INTO college(Id, name, is_active, created_by, updated_by) VALUES 
            (1, 'Đại học Cần Thơ', 1, '', ''),
            (2, 'Đại học FPT', 1, '', ''),
            (3, 'Đại học RMIT', 1, '', ''),
            (4, 'Đại học KHXH&NV (Đại học Quốc gia TP.HCM)', 1, '', ''),
            (5, 'Đại học KHTN (Đại học Quốc gia TP.HCM)', 1, '', ''),
            (6, 'Đại học Bách khoa Hà Nội', 1, '', ''),
            (7, 'Đại học Bách khoa TP HCM', 1, '', ''),
            (8, 'Đại học Trà Vinh', 1, '', ''),
            (9, 'Đại học Kinh tế Quốc dân', 1, '', ''),
            (10, 'Đại học Sân khấu - Điện ảnh Hà Nội', 1, '', ''),
            (11, 'Đại học Sân khấu - Điện ảnh TP.HCM', 1, '', ''),
            (12, 'Đại học Nam Cần Thơ', 1, '', ''),
            (13, 'Đại học Tây Đô', 1, '', ''),
            (14, 'Đại học Greenwich (Việt Nam)', 1, '', ''),
            (15, 'Đại Học Y Dược Cần Thơ', 1, '', ''),
            (16, 'Đại học Kỹ thuật - Công nghệ Cần Thơ', 1, '', ''),
            (17, 'Đại học Võ Trường Toản', 1, '', ''),
            (18, 'Đại học Mỹ thuật Công nghiệp Hà Nội', 1, '', ''),
            (19, 'Cao đẳng Cần Thơ', 1, '', ''),
            (20, 'Cao Đẳng Kinh Tế - Kỹ Thuật Cần Thơ', 1, '', ''),
            (21, 'Cao đẳng Y tế Cần Thơ', 1, '', '')
            `);
        await queryRunner.query(`INSERT INTO workplace(Id, name, is_active, created_by, updated_by) VALUES 
            (1, 'NFQ Asia', 1, '', ''),
            (2, 'FPT Software', 1, '', ''),
            (3, 'PTN Global', 1, '', ''),
            (4, 'Axon Active', 1, '', ''),
            (5, 'Delta Brains', 1, '', ''),
            (6, 'HiTa Tek', 1, '', ''),
            (7, 'VNG', 1, '', ''),
            (8, 'Viettel', 1, '', ''),
            (9, 'VNPT', 1, '', ''),
            (10, 'Bkav', 1, '', ''),
            (11, 'Intel Corporation', 1, '', ''),
            (12, 'Victoria Can Tho Resort', 1, '', ''),
            (13, 'Azerai Resort Can Tho', 1, '', ''),
            (14, 'Bệnh viện Hoàn Mỹ Cửu Long', 1, '', ''),
            (15, 'CGV', 1, '', ''),
            (16, 'TPBank', 1, '', ''),
            (17, 'The Coffee House', 1, '', ''),
            (18, 'Nestlé', 1, '', ''),
            (19, 'Dottie', 1, '', ''),
            (20, 'Vingroup', 1, '', ''),
            (21, 'Thế Giới Di Động', 1, '', ''),
            (22, 'Điện Máy Xanh', 1, '', ''),
            (23, 'Bách Hóa Xanh', 1, '', ''),
            (24, 'Vietnam Airlines', 1, '', ''),
            (25, 'VietJet Air', 1, '', ''),
            (26, 'Bamboo Airways', 1, '', '')
            `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
    }

}
